theme: jekyll-theme-slate
title: Welcome to this homepage!
description: This page is a homework assignmt for the university course [Social Graphs and Interactions](https://kurser.dtu.dk/course/02805) (02805)offered by [the Technical University of Denmark] (https://www.dtu.dk/)
permalink: /:categories/:year/:month/:day/:title:output_ext
