theme: jekyll-theme-slate
title: Welcome to this homepage!
description: This page contains an analysis of the videogame Crusader Kings 3 analysed with needlessly modern social science as an excuse to pick it for an assignment in the university course [Social Graphs and Interactions](https://kurser.dtu.dk/course/02805)

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
